/**
 * Generates the Planet Auto mark as SVG geometry.
 *
 * The mark on the shopfront is a turbine/iris: overlapping crescent blades
 * spiralling into a five-bolt wheel hub, ringed by a tilted orbit — the
 * "planet" half of the name. Blade crescents are the exposed part of
 * overlapping circles clipped to the rim, so the shapes are computed here
 * rather than hand-authored as path data.
 *
 *   node scripts/gen-logo.mjs > src/components/LogoMark.astro
 */

const C = 100; // centre of a 200×200 viewBox
const RIM = 64; // outer radius of the blade disc
// Blade circles smaller than the rim and pushed further out leave a thin
// spiralling crescent each; larger, closer circles just merge into a ball.
const BLADES = 6;
const BLADE_R = 43;
const BLADE_D = 50;
const HUB_R = 21;
const BOLT_RING = 11.5;
const BOLT_R = 3.6;
const BOLTS = 5;

const round = (n) => Number(n.toFixed(2));
const pt = (angleDeg, radius) => {
  const a = (angleDeg * Math.PI) / 180;
  return [round(C + Math.cos(a) * radius), round(C + Math.sin(a) * radius)];
};

/* ---------- blades ---------- */
// Drawn in order and clipped to the rim: each circle covers part of the one
// before it, and the sliver left showing is the blade.
const blades = [];
for (let i = 0; i < BLADES; i++) {
  const angle = -90 + (i * 360) / BLADES;
  const [cx, cy] = pt(angle, BLADE_D);
  // Alternate light and dark steel rather than ramping around the disc: a
  // monotonic ramp reads as a shaded sphere, which is the opposite of a
  // turbine. Alternation is what makes the blades separate as blades. The
  // small drift keeps the pairs from looking mechanically identical.
  const t = (i % 2 === 0 ? 0.06 : 0.94) + (i / BLADES) * 0.05;
  blades.push({ cx, cy, r: BLADE_R, tone: t });
}

/* ---------- bolt holes ---------- */
const bolts = [];
for (let i = 0; i < BOLTS; i++) {
  const [x, y] = pt(-90 + (i * 360) / BOLTS, BOLT_RING);
  bolts.push({ x, y });
}

/* ---------- orbit ring ---------- */
// An ellipse tilted about the disc. The full ellipse is stroked behind the
// blades, then the near section is stroked again on top, so the orbit reads as
// passing behind the wheel and back in front of it.
const RX = 95;
const RY = 35;
const TILT = -21;

/** Point on the untilted ellipse, in the ellipse's own frame. */
const ellipsePt = (deg) => {
  const a = (deg * Math.PI) / 180;
  return [round(C + Math.cos(a) * RX), round(C + Math.sin(a) * RY)];
};

// Near section: the lower arc that crosses in front of the disc.
const NEAR_FROM = 8;
const NEAR_TO = 172;
const [nx1, ny1] = ellipsePt(NEAR_FROM);
const [nx2, ny2] = ellipsePt(NEAR_TO);
const nearArc = `M ${nx1} ${ny1} A ${RX} ${RY} 0 0 1 ${nx2} ${ny2}`;

const steel = (t) => {
  // Ramp between the two steels sampled off the sign, widened so adjacent
  // blades separate instead of blurring into one another.
  const from = [0x8d, 0xa0, 0xaf];
  const to = [0x25, 0x38, 0x4a];
  const mix = from.map((v, i) => Math.round(v + (to[i] - v) * t));
  return `#${mix.map((v) => v.toString(16).padStart(2, '0')).join('')}`;
};

const svg = `---
/*
  GENERATED by scripts/gen-logo.mjs — edit the generator, not this file.

  The mark redrawn from the shopfront sign: a six-blade turbine around a
  five-bolt hub, inside a tilted orbit ring.
*/
interface Props {
  class?: string;
  title?: string;
}

const { class: className = 'size-10', title } = Astro.props;
const uid = Math.random().toString(36).slice(2, 8);
---

<svg
  class={className}
  viewBox="0 0 200 200"
  fill="none"
  role={title ? 'img' : undefined}
  aria-hidden={title ? undefined : 'true'}
  aria-label={title}
>
  <defs>
    <clipPath id={\`rim-\${uid}\`}>
      <circle cx="${C}" cy="${C}" r="${RIM}" />
    </clipPath>
  </defs>

  <!-- orbit, far side -->
  <ellipse
    cx="${C}" cy="${C}" rx="${RX}" ry="${RY}"
    transform="rotate(${TILT} ${C} ${C})"
    stroke="var(--logo-ring, #8A1729)" stroke-width="12"
  />

  <!-- turbine blades -->
  <g clip-path={\`url(#rim-\${uid})\`}>
    <circle cx="${C}" cy="${C}" r="${RIM}" fill="${steel(0)}" />
${blades
  .map(
    (b) =>
      `    <circle cx="${b.cx}" cy="${b.cy}" r="${b.r}" fill="${steel(b.tone)}" stroke="${steel(1)}" stroke-width="1.6" stroke-opacity="0.55" />`
  )
  .join('\n')}
  </g>

  <!-- orbit, near side, crossing in front of the wheel -->
  <path
    d="${nearArc}"
    transform="rotate(${TILT} ${C} ${C})"
    stroke="var(--logo-ring, #C8102E)" stroke-width="12" stroke-linecap="round"
  />

  <!-- hub -->
  <circle cx="${C}" cy="${C}" r="${HUB_R}" fill="#E8EBEE" />
  <circle cx="${C}" cy="${C}" r="${HUB_R}" stroke="${steel(1)}" stroke-width="2.5" />
${bolts.map((b) => `  <circle cx="${b.x}" cy="${b.y}" r="${BOLT_R}" fill="${steel(0.85)}" />`).join('\n')}
</svg>
`;

process.stdout.write(svg);
