/**
 * Vectorises the client-supplied logo bitmap into a two-colour SVG component.
 *
 * The artwork is flat-colour on white, so it separates cleanly: every pixel is
 * either the crimson swoosh, the steel spiral, or background. Each colour is
 * masked to its own 1-bit bitmap, traced separately, and the two path sets are
 * recombined — tracing the composite in one pass would weld the swoosh to the
 * spiral wherever they touch.
 *
 * potrace is not a project dependency — it pulls a jimp version with a known
 * advisory, and this only ever runs by hand when the artwork changes. Install
 * it for the run, then drop it again:
 *
 *   npm i -D potrace
 *   node scripts/trace-logo.mjs brand/logo-source.png > src/components/LogoMark.astro
 *   npm uninstall potrace
 */
import { Potrace } from 'potrace';
import sharp from 'sharp';

const SRC = process.argv[2];
if (!SRC) throw new Error('usage: node scripts/trace-logo.mjs <source.png>');

const { data, info } = await sharp(SRC)
  .removeAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

const { width, height, channels } = info;

/** Classify one pixel as 'red', 'grey' or 'bg'. */
function classify(r, g, b) {
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  if (max > 235 && max - min < 22) return 'bg'; // paper
  if (r > 110 && r > g * 1.55 && r > b * 1.55) return 'red';
  if (max < 225) return 'grey';
  return 'bg';
}

/** Build a 1-bit mask: the wanted colour black, everything else white. */
function mask(want) {
  const out = Buffer.alloc(width * height, 255);
  let count = 0;
  for (let i = 0, p = 0; i < data.length; i += channels, p++) {
    if (classify(data[i], data[i + 1], data[i + 2]) === want) {
      out[p] = 0;
      count++;
    }
  }
  return { out, count };
}

async function trace(want) {
  const { out, count } = mask(want);
  if (!count) throw new Error(`aucun pixel classé « ${want} »`);

  const png = await sharp(out, { raw: { width, height, channels: 1 } }).png().toBuffer();

  const potrace = new Potrace({
    threshold: 128,
    turdSize: 12, // drop specks left by JPEG-ish edges
    optCurve: true,
    optTolerance: 0.2,
    alphaMax: 1,
  });

  const svg = await new Promise((resolve, reject) => {
    potrace.loadImage(png, (err) => (err ? reject(err) : resolve(potrace.getSVG())));
  });

  // Keep the geometry, drop potrace's own wrapper and colours.
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  return { paths, count };
}

const grey = await trace('grey');
const red = await trace('red');

/*
  Trim the viewBox to the artwork. The source bitmap carries a wide white
  margin; left in, every size utility would be sizing mostly empty space and
  the mark would float off-centre in the header.
*/
let minX = width;
let minY = height;
let maxX = 0;
let maxY = 0;
for (let i = 0, p = 0; i < data.length; i += channels, p++) {
  if (classify(data[i], data[i + 1], data[i + 2]) === 'bg') continue;
  const x = p % width;
  const y = (p / width) | 0;
  if (x < minX) minX = x;
  if (x > maxX) maxX = x;
  if (y < minY) minY = y;
  if (y > maxY) maxY = y;
}
const pad = 4;
const vb = [
  Math.max(0, minX - pad),
  Math.max(0, minY - pad),
  Math.min(width, maxX + pad) - Math.max(0, minX - pad),
  Math.min(height, maxY + pad) - Math.max(0, minY - pad),
];
const aspect = (vb[2] / vb[3]).toFixed(4);

/*
  Centre of the wheel, for the spin. Taken from the steel mask alone, ignoring
  the columns the orbit sweeps through on either side: the ring is far wider
  than the wheel, so including it would drag the pivot off to the left and the
  spiral would wobble rather than turn.
*/
const colHasSteel = new Array(width).fill(false);
const rowHasSteel = new Array(height).fill(false);
const steelPerCol = new Array(width).fill(0);
for (let i = 0, p = 0; i < data.length; i += channels, p++) {
  if (classify(data[i], data[i + 1], data[i + 2]) !== 'grey') continue;
  const x = p % width;
  const y = (p / width) | 0;
  steelPerCol[x]++;
  colHasSteel[x] = true;
  rowHasSteel[y] = true;
}
// Only columns densely filled with steel belong to the disc; the ring's thin
// anti-aliased edge leaves a handful of pixels per column.
const peak = Math.max(...steelPerCol);
const dense = steelPerCol.map((n) => n > peak * 0.25);
const wheelX0 = dense.indexOf(true);
const wheelX1 = dense.lastIndexOf(true);
const wheelY0 = rowHasSteel.indexOf(true);
const wheelY1 = rowHasSteel.lastIndexOf(true);
const wheelCx = Math.round((wheelX0 + wheelX1) / 2);
const wheelCy = Math.round((wheelY0 + wheelY1) / 2);

process.stderr.write(
  `viewBox recadré : ${vb.join(' ')}  (ratio ${aspect})\n` +
    `centre de la roue : ${wheelCx},${wheelCy}\n`
);

process.stderr.write(
  `gris : ${grey.paths.length} tracé(s), ${grey.count} px\n` +
    `rouge: ${red.paths.length} tracé(s), ${red.count} px\n`
);

const component = `---
/*
  GENERATED by scripts/trace-logo.mjs from the client's logo artwork.
  Regenerate rather than editing by hand.

  Two colours, two variable hooks: the spiral takes --logo-steel and the orbit
  --logo-ring, so the mark can sit on the light page and on the dark footer
  without shipping a second file.

  The mark is landscape (ratio ≈ ${aspect}), not square — size it by width and
  let the height follow, or the orbit gets cropped.
*/
interface Props {
  class?: string;
  title?: string;
}

const { class: className = 'w-12', title } = Astro.props;
---

<svg
  data-logo-mark
  class={className}
  viewBox="${vb.join(' ')}"
  fill="none"
  role={title ? 'img' : undefined}
  aria-hidden={title ? undefined : 'true'}
  aria-label={title}
>
  <!--
    The spiral is its own group, and it is deliberately not animated.

    This mark is traced from a flat photograph of the sign, one pass per
    colour. Where the crimson orbit crosses the wheel the sign shows crimson,
    so the grey trace has that band missing — it was never drawn underneath.
    At rest the orbit covers the gap exactly and the wheel reads as whole;
    rotate the wheel and the gap travels out and opens a hole through the
    spokes. See the comment on the removed spin in src/scripts/motion.ts.

    data-logo-wheel keeps the hub at (${wheelCx}, ${wheelCy}) in viewBox units. Nothing reads
    it today; it is what a future spin would pivot on, once the original
    vector artwork exists and the wheel is a complete shape.
  -->
  <g
    data-logo-wheel="${wheelCx} ${wheelCy}"
    fill="var(--logo-steel, #6f7b89)"
    fill-rule="evenodd"
  >
${grey.paths.map((d) => `    <path d="${d}" />`).join('\n')}
  </g>
  <g fill="var(--logo-ring, #d81f26)" fill-rule="evenodd">
${red.paths.map((d) => `    <path d="${d}" />`).join('\n')}
  </g>
</svg>
`;

process.stdout.write(component);
